name: iif
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+24

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_hooks: ^0.18.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.3
  intl: ^0.17.0
  json_serializable: ^5.0.0
  shared_preferences: ^2.0.8
  solid_bottom_sheet: ^0.1.10

dev_dependencies:
  bloc_test: ^8.2.0
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  mockito: ^5.0.15

flutter:
  generate: true
  uses-material-design: true
