// Mocks generated by Mockito 5.0.15 from annotations
// in iif/test/domain/use_cases/delete_account_use_case_test.dart.
// Do not manually edit this file.

import 'package:iif/domain/include.dart' as _i2;
import 'package:iif/domain/repositories/accounts_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAccount_0 extends _i1.Fake implements _i2.Account {}

/// A class which mocks [AccountsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountsRepository extends _i1.Mock
    implements _i3.AccountsRepository {
  MockAccountsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Account> getAccountsOfType(_i2.AccountType? type) =>
      (super.noSuchMethod(Invocation.method(#getAccountsOfType, [type]),
          returnValue: <_i2.Account>[]) as List<_i2.Account>);
  @override
  _i2.Account saveAccount(_i2.Account? accountTemplate) =>
      (super.noSuchMethod(Invocation.method(#saveAccount, [accountTemplate]),
          returnValue: _FakeAccount_0()) as _i2.Account);
  @override
  String toString() => super.toString();
}
