// Mocks generated by Mockito 5.0.15 from annotations
// in iif/test/domain/use_cases/save_fund_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:iif/domain/include.dart' as _i2;
import 'package:iif/domain/repositories/funds_repository.dart' as _i3;
import 'package:iif/domain/repositories/operations_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeMoney_0 extends _i1.Fake implements _i2.Money {}

/// A class which mocks [FundsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundsRepository extends _i1.Mock implements _i3.FundsRepository {
  MockFundsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Fund> getFundsOfType(_i2.FundType? type) =>
      (super.noSuchMethod(Invocation.method(#getFundsOfType, [type]),
          returnValue: <_i2.Fund>[]) as List<_i2.Fund>);
  @override
  void saveFund(_i2.Fund? fund) =>
      super.noSuchMethod(Invocation.method(#saveFund, [fund]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [OperationsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOperationsRepository extends _i1.Mock
    implements _i4.OperationsRepository {
  MockOperationsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Money> calculateMoney(_i2.Fund? fund) =>
      (super.noSuchMethod(Invocation.method(#calculateMoney, [fund]),
              returnValue: Future<_i2.Money>.value(_FakeMoney_0()))
          as _i5.Future<_i2.Money>);
  @override
  void addOperationInitialInput(_i2.Fund? fund, _i2.Money? money) => super
      .noSuchMethod(Invocation.method(#addOperationInitialInput, [fund, money]),
          returnValueForMissingStub: null);
  @override
  _i5.Future<List<_i2.Operation>> getOperations(_i2.Fund? fund) =>
      (super.noSuchMethod(Invocation.method(#getOperations, [fund]),
              returnValue: Future<List<_i2.Operation>>.value(<_i2.Operation>[]))
          as _i5.Future<List<_i2.Operation>>);
  @override
  String toString() => super.toString();
}
